#config_version=3
mode:
    start_events: ball_starting
    stop_events: timer_skill_shot_complete, s_c_eject_active
    priority: 300

scoring:
    s_c_eject_active:
        score: 100000|block

timers:
    skill_shot:
        start_value: 12
        direction: down
        control_events:
          - event: balldevice_playfield_ball_enter
            action: start

light_player:
    mode_skill_shot_started:
      - show: flash_c_time_lock
        repeat: yes
        tocks_per_sec: 30
    mode_skill_shot_stopped:
      - show: flash_c_time_lock
        action: stop

slide_player:
    timer_skill_shot_tick:
        type: text
        text: "Shoot the Scoop: %ticks%"
